# NGCM Summer Academy 2016:

## Intermediate Python



Paul Chambers

P.R.Chambers@soton.ac.uk


## Foreword

* Bridge gap between (SWC) basics and IPython course
* Focus on applied data analysis
* Notebook live slideshow: [RISE](https://github.com/damianavila/RISE)

## Objectives

- Basics revision        ~ 30 mins
- Tuples, Dictionaries   ~ 30 mins
- OOP, Classes           ~ 90 mins
- Generators, Decorators ~ 60 mins


## Prerequisites

* Python 3, IPython 4+
* Numpy, Matplotlib
* Download material and exercises from github:
https://github.com/ngcm/summer-academy-2016

## Basics Refresher

* Lists
* `For` loops
* Numpy
* Matplotlib

### External Material
* If you missed the basics, try these:
    - [Hans Fangohr Python Book](http://www.southampton.ac.uk/~fangohr/training/python/pdfs/Python-for-Computational-Science-and-Engineering.pdf)
    - [Software Saved Basics Course](http://softwaresaved.github.io/NGCMGSoton-2015-06-21/novice/python/index.html) 

### Lists

* *Mutable* Container
* Handles mixed data types
* 

In [17]:
# List construction (including empty list + append), comprehension, additional methods

### If-Then-Else
*

In [18]:
# 

### For Loops

In [19]:
powers = [0, 1, 2, 3]
for power in powers:
    inv = 10 ** (power)
    print("10 to the power of {} is {}".format(power, inv))

10 to the power of 0 is 1
10 to the power of 1 is 10
10 to the power of 2 is 100
10 to the power of 3 is 1000


In [20]:
# Better to use range function here:
for i in range(4):
    print("10 to the power of {} is {}".format(i, 10**i))

10 to the power of 0 is 1
10 to the power of 1 is 10
10 to the power of 2 is 100
10 to the power of 3 is 1000


### Numpy
* Arrays and array operations
* Mathematical evaluations - fast on `np.array`
* Linear algebra
* 

In [21]:
import numpy as np

# basic usage: arange, linspace, array ops

In [22]:
# Performance: timeit list looping vs array looping vs array operations 

### Matplotlib
* Popular plotting library
* 

In [23]:
import matplotlib.pyplot as plt

In [24]:
# Live coding Bay....


## Tuples

* An *Immutable* List
* Faster than a List (fixed memory)
* Useful for **structured** data
* No *append* method - bad for sequential data

#### Example: Tuple Syntax

In [25]:
# Create a 'Name, Age' Tuple using bracket notation
my_tuple = ('Dave', 42)

print(type(my_tuple))
print(my_tuple)

<class 'tuple'>
('Dave', 42)


In [26]:
# Create Tuple using bracket notation
my_tuple2 = 'Bob', 24

print(type(my_tuple2))
print(my_tuple2)

<class 'tuple'>
('Bob', 24)


#### Example: Usage

In [27]:
# Tuple indexing
print(my_tuple[0])
print(my_tuple[1])

Dave
42


In [28]:
# Could make a list of tuples:
tups = [('Dave', 42), ('Bob', '24')]
# ... and then iterate over it
for tup in tups:
    print("{} is {} years old".format(tup[0], tup[1]))

Dave is 42 years old
Bob is 24 years old


#### Example: Tuple Unpacking

In [29]:
# Store multiple variables using tuples:
my_tuple = 'Dave', 42
a, b = my_tuple

print(a, b)

Dave 42


In [30]:
# Swap Variables using tuples:
b, a = a, b

print(a, b)

42 Dave


#### Example: When NOT to use a Tuple (1)

In [31]:
# extending or overwriting contents
print(my_tuple)

my_tuple[0] = 'Steve'

('Dave', 42)


TypeError: 'tuple' object does not support item assignment

#### Example: When NOT to use a Tuple (2)

In [32]:
# Sequences: Stick with a list
seq = []
for i in range(10):
    seq.append(i**2)

print(seq)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


In [33]:
# Or a numpy array:
print(np.arange(10)**2)

[ 0  1  4  9 16 25 36 49 64 81]


In [34]:
# Live coding Bay....


## Dictionaries

* Unordered set of `key` : `value` pairs
* Use curly braces - {} or `dict` keyword

#### Example: Fruit Prices Lookup Table - Construction

In [35]:
# Using the dict function:
fruit = [('apples', 2), ('bananas', 5), ('pears', 10)]
price_table = dict(fruit)
print(price_table)

{'pears': 10, 'bananas': 5, 'apples': 2}


In [36]:
# Short hand (Arguably neater)
price_table = {'apples': 2, 'bananas': 5, 'pears': 10}
print(price_table)

{'pears': 10, 'bananas': 5, 'apples': 2}


#### Example: Accessing values from keys

In [37]:
price_table = {'apples': 2, 'bananas': 5, 'pears': 10}

akey = 'apples'
print("The price of {} is {}p".format(akey, price_table[akey]))

The price of apples is 2p


#### Example: Iterating over a dictionary

In [38]:
# Iterating over the dictionary will iterate over its keys
d = {'apples': 2, 'bananas': 5, 'pears': 10}

for key in d:
    print("{} cost {}p".format(key, d[key]))

pears cost 10p
bananas cost 5p
apples cost 2p


In [39]:
# Or use the items method:
for key, val in d.items():
    print("{} cost {}p".format(key, val))

pears cost 10p
bananas cost 5p
apples cost 2p


#### Example: When NOT to use a Dictionary

In [40]:
# Hoping for ordered data:
alpha_num = {'a': 0, 'b': 1, 'c': 2}

for i, key in enumerate(alpha_num.keys()):
    print("{} has a value of {}".format(key, i))   # This is wrong

b has a value of 0
a has a value of 1
c has a value of 2


#### Example: Dictionary unpacking using '**'

In [41]:
d = {'a': 1, 'b': 2}
d.pop('a')

1

In [42]:
# Live coding Bay....


> [Exercise: ](exercises/01-Tuples_Dictionaries.ipynb)

# Intro to Python OOP

#### (For The Classy Programmer)

><div align="center" style="width:600px; text-align:centered; font-style:italic; font-size:18pt">
"In the class-based object-oriented programming paradigm, object refers to a particular instance of a class where the object can be a combination of variables, functions, and data structures."
></div>


## Why OOP?

* Naturally structured data
* Functions used in context
* Reduce duplicate code
* Maintainability in large codes/software
* [Many other reasons](http://inventwithpython.com/blog/2014/12/02/why-is-object-oriented-programming-useful-with-an-role-playing-game-example/)

### OOP in Scientific Computing
* Java, `C++` and Python designed for OOP
* **Everything** in Python is an object
* Scientific libraries, visualisation tools etc.
* Pseudo Object Orientation in `C` and `Fortran`

### How can this course help me
* Language in OOP is very different
    - Learn language used in eg. C++, Java
* Ability to **read** code is essential
* Write/migrate code for community library
    - Better world! Work recognition etc...

###  Language: Four Fundamental Concepts

* *Inheritance*
    - Reuse code by deriving from existing classes
    
* *Encapsulation*
    - Data hiding

###  Language: Four Fundamental Concepts (2)

* *Abstraction* 
    - Simplified representation of complexity
    
* *Polymorphism*
    - API performs differently based on data type

**Note:** Encapsulation is sometimes also used in OOP to describe the grouping of data with methods. It is however more common for texts to use it to describe the hiding of data as will be done here.

Useful explanations of these concepts for Python can also be found [here](http://zetcode.com/lang/python/oop/)

### Material we will cover
* `Classes`
* Initialization and `__init__`
* Python 2.X vs 3.X
* `self`
* Encapsulation with underscore '`_`'
* Inheritance
* Magic operators

## Structured data: Numpy dtypes
* Not a class, but motivational example
* Structured associative data
* Similar to C `struct`
* Identifiers to indicate data type

#### Example: Data about people

In [45]:
with open('data/structured_data.txt', 'w') as f:
    f.write('#Name    Height    Weight\n')
    f.write('John     180    80.5\n')
    f.write('Paul     172    75.1\n')
    f.write('George   185    78.6\n')
    f.write('Ringo    170    76.5\n')

In [46]:
# Notice that the argument is a list of tuples
dt = np.dtype([('Name', np.str_, 16), ('Height', np.int32),
                ('Weight', np.float64)])
data = np.loadtxt('data/structured_data.txt', dtype=dt)

print(data)

[("b'John'", 180, 80.5) ("b'Paul'", 172, 75.1) ("b'George'", 185, 78.6)
 ("b'Ringo'", 170, 76.5)]


In [109]:
print(data['Name'])
print("{} has weight {}".format(data[0]['Name'], data[0]['Weight']))

["b'John'" "b'Paul'" "b'George'" "b'Ringo'"]
b'John' has weight 80.5


In [48]:
# Live coding Bay....


> [Exercise: Load image data with dtype structured array](exercises/02-dtypes.ipynb)

> ... Data is structured, but not elegant

## Classes: Basics
* Attributes (data)
* Methods    (Functions operating on the attributes)
* 'First class citizens': Same rights as core variables
    - pass to functions, store as variables etc.

#### Example: Numpy arrays showing how it's done

In [70]:
# Numpy arrays are classes
import numpy as np
a = np.array([0, 1, 6, 8, 12])
print(a.__class__)
print(type(a))

# We want to operate on the array: try numpy cumulative sum function
print(np.cumsum(a))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
[ 0  1  7 15 27]


In [111]:
np.cumsum('helloworld')   # Should we expect this to work?

TypeError: cannot perform accumulate with flexible type

#### Example: Numpy arrays showing how it's done (ctd.)

* We only know what a cumulative sum means for a narrow scope of data types

* Group them together with an object!

In [86]:
# cumsum is a method belonging to a
a.cumsum()

array([ 0,  1,  7, 15, 27])

#### Example: Simple class

In [98]:
class Greeter:
    name = 'Bob'             # Attribute
    def hello(self):         # Method (more on 'self' later)
        print("Hello World")

agreeter = Greeter()         # 'Instantiate' the class
print(agreeter)
print(dir(agreeter))

['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', 'hello', 'name']


In [100]:
agreeter.hello()
print("My name is {}".format(agreeter.name))

Hello World
My name is Bob


## Classes: Initialisation and `self`

* ```__init__``` class method
* Called on creation of an instance
* Convention: `self` = instance
* *Implicit passing* of instance, *explicit receive*


**Note:** Passing of `self` is done implicitly in other lagnauges e.g. C++ and Java, and proponents of those languages may argue that this is better. "*Explicit is better than implicit*" is [simply the python way](https://www.python.org/dev/peps/pep-0020/).

### Classes: Initialisation vs Construction
* Initialisation is not *technically* Construction
* `__new__` '*constructs*' the instance before `__init__`
* `__init__` then initialises the content

**More info:** The Constructor *creates* the instance, and the Initialiser *Initialises* its contents. Most languages e.g. C++ refer to these interchangably and perform these steps together, however the new style classes in Python splits the process.

The difference is quite fine, and for most purposes we do not need to redefine the behaviour of `__new__`. This is discussed in several Stack Overflow threads, e.g.

* [Python (and Python C API): `__new__` versus `__init__`](http://stackoverflow.com/questions/4859129/python-and-python-c-api-new-versus-init)

* [Python's use of `__new__` and `__init__`?](http://stackoverflow.com/questions/674304/pythons-use-of-new-and-init)

#### Example: Class Initialisation

In [88]:
class A:
    def __init__(self):
        pass

a_instance = A()
print(type(A))

<class 'type'>


### Old classes vs New classes

* Inheritance behaviour is different
* New classes inherit from `object` (more later...)
* Old classes removed in Python 3

#### Example: New class default Python 3

In [89]:
class OldSyntax:
    pass

class NewSyntax(object):  # This mean 'inherit from object'
    pass
    
print(type(OldSyntax))    # Would give <type 'classobj'> in Python 2
print(type(NewSyntax))

<class 'type'>
<class 'type'>


* Backwards compatibility: inherit `object` in Py3

#### Example: Defining Instance attributes/methods

In [91]:
class A

SyntaxError: invalid syntax (<ipython-input-91-7c8ee6383425>, line 1)

#### Example: Class attributes vs instance attributes

In [92]:
import numpy as np
class Container:
    data = np.linspace(0, 1, 5)

a, b = Container(), Container()
print(a.data, b.data)

[ 0.    0.25  0.5   0.75  1.  ] [ 0.    0.25  0.5   0.75  1.  ]


In [94]:
a.data = 0                     # Creates new INSTANCE attribute
Container.data = 100           # Overwrites CLASS attribute
print(a.data)
print(b.data)

100
0


**Note**: There's a couple of things going on in this example which are worth elaborating on. By specifying `ClassName.Attribute`, in this case `Container.data = 100` we've overwritten the value of `data` that EVERY instance of the `Container` class will access. Hence printing `b.data` gives the expected result.

By setting `a.data` at the same time, we have set an `instance`

This could create a hard to track bug. To avoid this, 

See [this material](http://www.python-course.eu/python3_class_and_instance_attributes.php) for a more in-depth look at class vs instance attributes.

#### Example: Implicit vs Explicit passing Instance

In [ ]:
class Container:
    def __init__(self, data):
        self.data = data

    def print_data(self):
        print(self.data)

a = Container(data=1)
b = Container(data=2)

a.print_data()          # <<< This is better
Container.print_data(b)

> [Exercise](exercises/03-Classes_basics.ipynb)

## Classes: Encapsulation
* Hiding data from users (and develop
* 
* Use underscores '`_`' or '`__`'

#### Example

In [ ]:
# Live coding Bay....


## Classes: Inheritance

* 

#### Example:

In [ ]:
# 

## Classes: Magics

#### Example: 

In [ ]:
# Live coding Bay....


* [Exercise](exercises/04-Classes_pt2.ipynb)

## Generators

* 

#### Example

In [ ]:
# 

In [ ]:
# Live coding Bay....


> [Exercise](exercises/05-Generators.ipynb)

## Decorators

#### Example

In [ ]:
# Live coding Bay....


> [Exercise](exercises/06-Decorators.ipynb)

## Extra Material

* Harder exercise (if time)

* Should test your knowledge from this course

> [Exercise: Predator Prey ](exercises/07-Decorators.ipynb)


* Other things worth looking at (an incredibly biased opinion):
    - [Building Pythonic Packages with setuptools](https://pythonhosted.org/an_example_pypi_project/setuptools.html)
    - [Unit testing with py.test](https://pytest.org/latest/contents.html)
    - [Conda Environments](http://conda.pydata.org/docs/using/envs.html)


## Summary
* 

In [57]:
from IPython.core.display import HTML
def css_styling():
    sheet = './css/custom.css'
    styles = open(sheet, "r").read() 
    return HTML(styles)
css_styling()